### ISSUE TITLE
某些转换后的歌曲在walkman上播放到末尾出现错误

### ISSUE THREAD

**Issue by LambdaHL** [yoki123/ncmdump#10]
歌曲为Aimer的I beg you，转换为flac后在mediago和网易云中可以正常播放完毕，导入walkman a45后播放至4:19时出现Cannot play,file format is not supported

**Comment by yoki123** [comment]
没设备无法验证😞，`播放到末尾出现错误`，我猜测上一首歌末尾的时候会预加载下一首，也就是说可能是列表中下一首歌有问题而不是当前文件有问题。
