### ISSUE TITLE
Mac版转换后自动添加标题、歌手、唱片等信息会乱码

### ISSUE THREAD

**Issue by xiebruce** [yoki123/ncmdump#11]
用空格查看，这些信息全是乱码
![image](https://user-images.githubusercontent.com/13575500/62265136-82220c00-b455-11e9-873c-e33b0173473a.png)

然后我不得不用修改这些信息的工具去修改
![image](https://user-images.githubusercontent.com/13575500/62265131-7f271b80-b455-11e9-8967-d4b3426dc740.png)

这个原因应该是歌是用Win添加的信息，Win上的编码不是UTF-8导致的。

**Comment by yoki123** [comment]
原曲解码出来就包含tag信息，编码为UTF-16，ncmdump不会对原有tag进行重写，只对没有tag信息的进行补全（补全的时候使用UTF-8）。建议使用其他工具来转换tag的编码，可以参考这个https://aaronmix.net/2011/06/solution-to-itunes-migration-from-win2mac/

**Comment by xiebruce** [comment]
哦哦，建议读取一下原曲的信息然后重写一遍(其实就相当于转码一遍)，这样可以防止转换后的音乐信息乱码，用另外的工具感觉有点麻烦，而且还是win的。

**Comment by yoki123** [comment]
这个下一版本会考虑

**Comment by xiebruce** [comment]
@yoki123 好的，谢谢！

**Comment by Hades13th** [comment]
我也存在这个问题，转换后会乱码

**Comment by Jeffre-hub** [comment]
为什么我使用她在WIN10下无法正常使用呢？

**Comment by yoki123** [comment]
@Jeffre-hub  能具体说明下错误信息吗？有截图最好

**Comment by Jeffre-hub** [comment]
可能于win10下不兼容，无图形化界面，无进程项，系统修复以win8模式兼容运行失败。

Yoki <notifications@github.com> 于 2020年3月23日周一 下午3:22写道：

**Comment by Jeffre-hub** [comment]
我现在还没有能力独自解决这个问题，请求帮助。

jeffre chou <choujeffre@gmail.com> 於 2020年3月23日週一 下午7:42寫道：

**Comment by Jeffre-hub** [comment]
抱歉，请原谅我的无知。问题已经解决了，我为我的无知感到羞愧。

jeffre chou <choujeffre@gmail.com> 於 2020年4月4日週六 上午11:51寫道：

**Comment by yoki123** [comment]
@Jeffre-hub 没事，也可能是文档说明不到位呢，有其他问题也欢迎提出

**Comment by xiebruce** [comment]
@yoki123 我发现他这些话都是英文翻译成中文的，应该是个老外吧哈哈
