### ISSUE TITLE
个别歌转换报错

### ISSUE THREAD

**Issue by xiebruce** [yoki123/ncmdump#12]
就是这首歌：[陈奕迅 - 苦瓜.ncm.zip](https://github.com/yoki123/ncmdump/files/3463500/-.ncm.zip)，其它的歌都没问题，目前就遇到这一次，是歌的文件的问题吗？可是这也是直接从网易云下的呀，如果个有问题，那其它的应该也会有问题吧？

这是报错信息：
```
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
main.processFile(0x7ffeefbff99c, 0x39)
	D:/Projects/ncmdump/src/ncmdump/main.go:157 +0x49c
main.main()
	D:/Projects/ncmdump/src/ncmdump/main.go:452 +0x6b6
```

**Comment by yoki123** [comment]
编译了[v0.3.0](https://github.com/yoki123/ncmdump/releases/tag/v0.3.0) ，这个版本有越界判断，可以解决这个问题

**Comment by xiebruce** [comment]
@yoki123 谢谢，不过我是Mac，之前的都有Mac版，这次怎么只有win😂

**Comment by yoki123** [comment]
mac的刚刚上传了

**Comment by xiebruce** [comment]
@yoki123 谢谢，下载了试了试，原来我说的那个歌“陈奕迅 - 苦瓜.ncm.zip”转出来是flac格式的“陈奕迅 - 苦瓜.flac”，怪不得之前报错，但是现在也有报错“fLaC head incorrect”：
```
2019/08/07 19:51:29 Adding music name
2019/08/07 19:51:29 Adding album name
2019/08/07 19:51:29 fLaC head incorrect
```
虽然有“fLaC head incorrect”这个报错，不过还是可以转换成功并且转换出来的flac文件也能正常播放。

不知道这个转出来是flac格式还是mp3格式这个是由谁决定的呢？是由ncm本身决定的是吗？你这个工具有没有一个功能，如果我想要mp3格式，即使它本来转出来的应该是flac但最终也输出mp3呢？

**Comment by yoki123** [comment]
后缀是由ncm中meta信息的format来决定，文件实际格式是由文件头决定。
这ncm文件中meta信息中format是`flac`,
`{"musicId":0,"musicName":"","artist":null,"bitrate":0,"duration":0,"format":"flac"}`
 实际解码出来的音乐文件头部却是mp3 

![image](https://user-images.githubusercontent.com/2094104/62672596-ef8de980-b9cd-11e9-8071-2f426a51e5f2.png)

也就是说这个ncm文件本身就是有问题的，meta的format和文件实际格式不符，石锤官方伪无损？
至于你说的强制输出mp3格式那涉及转码了，dump工具只做好dump就行了，因为只有需要解码ncm的时候才会想用到ncmdump，其他需求都有更好的工具代替。
最后，播放器是根据头部信息来使用对应的解码器，后缀不会影响播放。

**Comment by xiebruce** [comment]
原来是这样，那这个issue算是解决了问题也解决了疑问了，感谢大佬！
