### ISSUE TITLE
请教下，AES的key怎么获取到的？

### ISSUE THREAD

**Issue by ylxiong** [yoki123/ncmdump#15]
请教下，AES的key怎么获取到的？

**Comment by yoki123** [comment]
[README.md](https://github.com/yoki123/ncmdump/blob/master/README.md)中有说明，这个项目一开始是直接翻译[anonymous5l/ncmdump](https://github.com/anonymous5l/ncmdump/blob/f575da02427aa5f1eab95c5ee2a78e44d6e155e7/main.cpp#L17)到Go语言，来解决编译依赖问题，所以key都是从这个项目抄过来的。

至于第一个人怎么拿到key的，应该是反编译官方播放器客户端拿到的，原因如下
1. 播放器也需要读取ncm格式，客户端就包含有解密逻辑
1. 解密算法是AES，是对称加密
1. 恰巧所有的文件都使用了相同的AES key，那么key在客户端播放器中就是一个常量
