### ISSUE TITLE
好像不能从命令中看版本

### ISSUE THREAD

**Issue by xiebruce** [yoki123/ncmdump#16]
有时候太久不用，都忘了自己下载的哪个版本了，加一个能查看版本好点

**Comment by yoki123** [comment]
嗯，到目前为止，之前所有版本都没有加版本号，其实所有迭代也没有特别大的更新，都是一些小优化。
然后呢，加版本号之后也只有后续版本能看到版本号。

**Comment by yoki123** [comment]
带版本号的已发布 https://github.com/yoki123/ncmdump/releases/tag/v0.3.4

**Comment by xiebruce** [comment]
感谢！
