### ISSUE TITLE
把ncm文件转成mp3 或者flac文件后，客户端不认怎么办？

### ISSUE THREAD

**Issue by W-quan** [yoki123/ncmdump#17]
转换后的文件就放到原来的目录下， 网易云还是显示为下载，怎么才能关联起来呢？

**Comment by yoki123** [comment]
你把转换后的的文件拷贝到另一个新文件夹，然后在网易云的本地音乐中添加那个新文件夹

**Comment by W-quan** [comment]
忘了说，我的MacOS。没这个功能

**Comment by yoki123** [comment]
能不能提供一个MacOS下载的mp3或者ncm源文件，我没有mac设备

我用windows下载的和[知乎上的答主](https://www.zhihu.com/question/46370870/answer/1314152754)的comment格式不一样

![v2-5cf1671d6e3c48f57c18124ec81af58d_r](https://user-images.githubusercontent.com/2094104/102455445-95e60680-407a-11eb-97cb-89a1cd8ddefd.jpg)

![image](https://user-images.githubusercontent.com/2094104/102455514-b57d2f00-407a-11eb-8e66-757a92ded5bd.png)

**Comment by W-quan** [comment]
<img width="400" alt="图片" src="https://user-images.githubusercontent.com/9608466/102458383-1eff3c80-407f-11eb-8760-ba131a8a3c93.png">


[Simon & Garfunkel - Scarborough Fair (Canticle).mp3.zip](https://github.com/yoki123/ncmdump/files/5707717/Simon.Garfunkel.-.Scarborough.Fair.Canticle.mp3.zip)

**Comment by W-quan** [comment]
好像我跟你的一样，我是直接用 anonymous5l/ncmdump的， 并没有用你这个。

你这个有添加上面的信息？

**Comment by yoki123** [comment]
没有，ncm的这个comment直接被解码了，我可以试试把这个comment信息拷贝到mp3文件里

**Comment by yoki123** [comment]
我检查了代码，ncmdump有对mp3写入comment，而flac格式写入DESCRIPTION没有成功，我这边在windows下测试，mp3可以识别到

https://github.com/yoki123/ncmdump/blob/master/ncmdump.go#L193
https://github.com/yoki123/ncmdump/blob/master/tag.go#L82
https://github.com/yoki123/ncmdump/blob/master/tagger.go#L203

**Comment by W-quan** [comment]
问题就是flac， MacOS 下需要用系统自带的音乐导入文件，然后分享到网易云音乐。 但是 系统自带的那个立即居然不能识别flac

**Comment by W-quan** [comment]
https://github.com/anonymous5l/ncmdump/blob/f9f6e2f1746d7eaf0e2c08eb61fde91d94dbfbb5/ncmcrypt.cpp#L221

```c++
tag->setComment(TagLib::String("Create by netease copyright protected dump tool. author 5L", TagLib::String::UTF8));
```
它这里没有copy进去

**Comment by yoki123** [comment]
新发布了[v0.3.5](https://github.com/yoki123/ncmdump/releases/tag/v0.3.5)，修复了flac写入失败的问题，windows下已测试通过，Mac就需要你自己跑下看看了

**Comment by W-quan** [comment]
![图片](https://user-images.githubusercontent.com/9608466/102603323-93a8a880-415d-11eb-8a5f-0fb922fcceaf.png)
<img width="265" alt="图片" src="https://user-images.githubusercontent.com/9608466/102603352-9e633d80-415d-11eb-8973-757d3d0aa0ef.png">


没有看到有comment。 无法确定是本来几没有还是写入失败。是不是应该打印个log呢？

mp3是有的

**Comment by W-quan** [comment]
链接: https://pan.baidu.com/s/1CfbHH-6fDBlLkFHQOdIvWg  密码: rgcn


文件给你测测

**Comment by yoki123** [comment]
![win2](https://user-images.githubusercontent.com/2094104/102605548-66112e80-4160-11eb-84f4-c136c1bc6713.png)
![win](https://user-images.githubusercontent.com/2094104/102605572-6ad5e280-4160-11eb-8f37-3d25d64cde83.png)
![win4](https://user-images.githubusercontent.com/2094104/102605581-6c9fa600-4160-11eb-9c86-baf737d5cc85.png)

Windows下没有问题，空了我找个mac设备看看

**Comment by W-quan** [comment]
奇怪的是调用了 tag->setComment(), 但是不知为何没写进去。

经过我的实验， comment的内容就是 swapModifyData 那段。  C++小白😂， 难道是taglib这个库的问题？

![image](https://user-images.githubusercontent.com/9608466/102680137-aae4a600-41f0-11eb-8095-7cbc06936b90.png)

![image](https://user-images.githubusercontent.com/9608466/102680158-d36ca000-41f0-11eb-9913-36966cf459b7.png)

**Comment by W-quan** [comment]
原来使用系统的文件管理器查看 flac是看不到Comments的。 我用了第三方的工具查看是有comment的， 但是title 那些却没了

<img width="1464" alt="image" src="https://user-images.githubusercontent.com/9608466/102683830-9ca58280-420e-11eb-8674-d4a1ab3caffe.png">

**Comment by donly** [comment]
macOS 11.x 下用 ffmpeg 查看是有 comment，标题也有，但是没了专辑
![image](https://user-images.githubusercontent.com/848691/102966289-8fe49f80-452a-11eb-82f1-b1ac4afb2dd6.png)

**Comment by yoki123** [comment]
title,album确实还有点问题，等我修复下
https://github.com/yoki123/ncmdump/blob/master/tag/tag.go#L65

**Comment by yoki123** [comment]
![223](https://user-images.githubusercontent.com/2094104/102969215-472fe500-4530-11eb-8979-083e081622e1.png)

**Comment by donly** [comment]
这效率真高！
怎么测试，不会 Go

**Comment by yoki123** [comment]
@donly 刚编译了新版本[v0.3.6](https://github.com/yoki123/ncmdump/releases/tag/v0.3.6)

**Comment by W-quan** [comment]
作者不是提供了执行文件吗， 也可以看我的修改的 [https://github.com/W-quan/ncmdump](https://github.com/W-quan/ncmdump) 👀

**Comment by yoki123** [comment]
暂时没有收到任何新的异常反馈，先关闭这个issues了

**Comment by ZbinH2O** [comment]
<img width="265" alt="QQ20210114-114306@2x" src="https://user-images.githubusercontent.com/6178275/104542150-ef335c80-565d-11eb-9db8-8d7870bc1bbe.png">
<img width="440" alt="QQ20210114-114756@2x" src="https://user-images.githubusercontent.com/6178275/104542835-366e1d00-565f-11eb-8720-df61508345db.png">

这边用macOS 11.1,然后使用v0.3.6版本测试了一下ncm转mp3,发现转出来不带有任何专辑信息..用回v0.3.0版本的话,导出正常..之前试过是从v0.3.1版本开始,转换后都是信息缺失

**Comment by donly** [comment]
我特意测试了下，这个问题应该和歌曲有关，我随便找了首发现又没问题。
![image](https://user-images.githubusercontent.com/848691/104676602-aabdc480-5722-11eb-80b3-b89c76177ac6.png)

建议以这两个 case 将问题重现测试 @yoki123

**Comment by W-quan** [comment]
@ZbinH2O 不建议用系统 简介查看， 下个第三方软件看。 系统简介有点看的了，有的不显示

**Comment by donly** [comment]
> @ZbinH2O 不建议用系统 简介查看， 下个第三方软件看。 系统简介有点看的了，有的不显示

经验之谈吗哈哈，但老街转换后确实丢了信息，上面我的回复中的图片是苹果音乐App 的详情，另外用 ffmpeg 看了也是没有：

```
Input #0, mp3, from '/Users/donly/Music/网易云音乐/李荣浩 - 老街.mp3':
  Metadata:
    encoder         : Lavf57.25.100
  Duration: 00:05:18.82, start: 0.025057, bitrate: 320 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s
    Metadata:
      encoder         : Lavc57.24
```

**Comment by ZbinH2O** [comment]
<img width="721" alt="QQ20210115-154620@2x" src="https://user-images.githubusercontent.com/6178275/104696211-dfdd0d80-5748-11eb-8bf7-d145ebef0d30.png">
我也使用 @donly 那首歌测试了一下,的确可以成功..

@W-quan 至于老街的话,我使用苹果自带音乐APP打开,也是没有任何信息..

**Comment by yoki123** [comment]
我用win测了好像没问题，老街这首也没问题；
album、airtist、title转出来的mp3就有了，然后ncmdump写入的comment也是正确的；
![20210116201938](https://user-images.githubusercontent.com/2094104/104811704-54db4080-5838-11eb-8351-3f559cda4f07.png)

下个版本我把tag相关信息打印出来看看吧，这样方便找问题
