### ISSUE TITLE
老哥, 有无收到 DMCA 警告呀~

### ISSUE THREAD

**Issue by wolfcon** [yoki123/ncmdump#20]
明日就无了...有无联系方式@@ 

> Dear Sir/Madam,
> 
> I have already read and understand GitHub's Guide to Filing a DMCA Notice.
> 
> I represent 杭州网易云音乐科技有限公司, which is a China company with company registration code: 91330108MA27XNADXX registered in China.
> 
> Our company owns or is the licensee of the intellectual property rights in, notably, the “网易云音乐” trademarks, logos, the general structure of the website “music.163.com” and the corresponding PC/MAC software application “网易云音乐”,which is also available under iOS, and Android as mobile application, and all the items/elements in the above system (for example but not only limited to the logos, trademarks, domain names, content, and their associated elements such as pictures, texts, animations, sound effects .etc.). Every musical or non-musical content on software/Application “网易云音乐” is protected by copyright law.
> 
> “.NCM” is a file format developed by Netease, used as one of the TPM solution to protect copyrights from unfair re-distributions. “.NCM” is an encryption method and it controls the play of “.NCM” file, make the downloaded file only playable in Netease Cloud Music players(under PC, Mac, iOS, and Android).
> 
> We have discovered the following links in Github:
> 
> https://github.com/anonymous5l/ncmdump
> 
> https://github.com/anonymous5l/ncmdump-gui
> 
> https://github.com/NoColor2/ncmdump
> 
> https://github.com/yoki123/ncmdump
> 
> https://github.com/nondanee/ncmdump
> 
> https://github.com/real-zony/ncmdump
> 
> https://github.com/orange1423/ncmDumpGUI
> 
> https://github.com/roller-coaster/NcmDump
> 
> https://github.com/Yeamy/ncmdump
> 
> https://github.com/LuRenJiasWorld/NcmDump-Online
> 
> https://github.com/eson-sheng/ncmdump
> 
> https://github.com/orange1423/ncmDumpGUI
> 
> https://github.com/unlock-music/unlock-music
> 
> https://github.com/thinkAfCod/ncmdump
> 
> https://github.com/yuxiqian/ncm-peeler-swift
> 
> https://github.com/jiayuqiu/ncm2mp3
> 
> https://github.com/duanfuqiang1128/ncm-switch
> 
> The developers have knowingly procured or offered to others, without our authorization, a method especially dedicated to the circumvention of our effective TPM measures, in order to convert Netease’s protected” .NCM ” file format into normal music file format, for example “.MP3”.
> 
> Therefore I am asking Github would take action immediately, take down the projects listed above, and their forked versions also.
> 
> The above is a brief description of the violations at stake and is not meant to be a complete statement of our company's prejudice, rights and remedies in connection with the subject matter of this email. All such rights and remedies are expressly reserved, including the rights and remedies of our licensors.
> 
> Based on the representative number of forks I have reviewed, I believe that all or most of the forks are infringing to the same extent as the parent repository.
> 
> I have a good faith belief that use of the copyrighted materials described above on the infringing web page is not authorized by the copyright owner, or its agent, or the law. I have taken fair use into consideration.
> 
> I swear, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner, or am authorized to act on behalf of the owner, of an exclusive right that is allegedly infringed.
> 
>  
> 
> With Regards,
> 
> [private]
> 
> [private]
> 
> Netease Legal 网易法务部
> 
> 杭州市滨江区网商路399号

**Comment by MadCreeper** [comment]
网易真是不当人啊

**Comment by immortalt** [comment]
oh!!!

**Comment by yoki123** [comment]
放了个假确实收到了DMCA，准备转私有了
