### ISSUE TITLE
把 ReadMe 里的网页版链接删掉吧

### ISSUE THREAD

**Issue by kasuganosoras** [yoki123/ncmdump#5]
为了防止水表爆炸影响我出境，网站我下了……
目前 V2EX 的帖子我也申请删除了，bilibili 的视频也删了……
谢谢！

**Comment by kasuganosoras** [comment]
目前访问网页版会自动 301 重定向到大佬的这个项目，希望越做越好，帮助更多人吧

**Comment by yoki123** [comment]
已删
