### ISSUE TITLE
移动文件失败

### ISSUE THREAD

**Issue by SteveZhu0241** [yoki123/ncmdump#6]
当导出目录选择桌面或Windows音乐库等位置的时候，在文件转换完成之后会提示“移动文件失败”。即使给了管理员权限也没用。并且，如果给了应用管理员权限，会导致无法拖动音乐文件至主界面。

（Ps. 想请问下转换时的缓存目录在哪里...

**Comment by yoki123** [comment]
导出没有使用缓存，直接往目标文件夹写入的，能不能贴一个具体错误信息，我看下是怎么回事

**Comment by SteveZhu0241** [comment]
![image](https://user-images.githubusercontent.com/43177065/47648752-e4dc3380-dbb5-11e8-8e1a-9c5c27638fa6.png)

**Comment by SteveZhu0241** [comment]
已经确定了桌面没问题，抱歉。
但是若以Windows自带音乐库作为导出目录，依然提示移动文件失败。

**Comment by yoki123** [comment]
你用的这个软件不是这个项目的哦。

**Comment by yoki123** [comment]
没事，你可以联系工具本人或者使用其他gui代替https://github.com/anonymous5l/ncmdump-gui
